global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100'
  - job_name: 'mysql-exporter'
    static_configs:
      - targets:
        - 'mysql-prefork-exporter:9104'
  - job_name: 'apache-prefork-exporter'
    static_configs:
      - targets:
        - 'apache-prefork-exporter:9117'
  - job_name: 'docker'
    static_configs:
      - targets:
        - 'localhost:9323'
